import { describe, it, expect } from 'vitest';
import type { SvApi } from 'sv';
import { applyBaseMode } from '../packages/svforge/src/modes/base';
import { applyDashboardMode } from '../packages/svforge/src/modes/dashboard';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

/**
 * #343 — Run design checks from `bun run check`.
 *
 * The generated `check` script chains svelte validation AND the
 * self-contained design-system checker (node svforge-check.mjs — local,
 * deterministic, no network install). Severity contract: the checker exits
 * non-zero on ERROR and zero on WARN-only, so plain `&&` chaining preserves
 * "ERROR fails the command, WARN stays informational".
 *
 * The template package.json files and the script generated by the addon
 * modes must stay consistent.
 */

const ROOT = join(import.meta.dirname, '..');

type FakeSv = {
	dependencies: string[];
	devDependencies: string[];
	files: Map<string, string>;
	dependency: (name: string, version: string) => void;
	devDependency: (name: string, version: string) => void;
	file: (path: string, transform: (content: string) => string) => void;
};

function fakeSv(): FakeSv {
	const sv: FakeSv = {
		dependencies: [],
		devDependencies: [],
		files: new Map(),
		dependency(name) {
			this.dependencies.push(name);
		},
		devDependency(name) {
			this.devDependencies.push(name);
		},
		file(path, transform) {
			// Accumulate like the real sv add: a second sv.file('package.json')
			// transform reads what the previous mode wrote.
			const existing = this.files.get(path);
			const seed = existing ?? (path === 'package.json' ? '{"scripts":{}}' : '');
			this.files.set(path, transform(seed));
		}
	};
	return sv;
}

// FakeSv implements the SvApi surface the modes actually use; the unused
// required SvApi members are stubbed out at this single boundary.
const asSvApi = (sv: FakeSv): SvApi => sv as unknown as SvApi;

function generatedCheckScript(files: Map<string, string>): string {
	const pkg = JSON.parse(files.get('package.json') ?? '{}');
	return pkg.scripts?.check ?? '';
}

describe('bun run check chains the design-system check (#343)', () => {
	it('base mode chains svforge-check.mjs after the svelte checks', () => {
		const sv = fakeSv();
		applyBaseMode(asSvApi(sv), { '/lib/base.ts': 'base' });
		const check = generatedCheckScript(sv.files);
		expect(check).toContain('svelte-check');
		expect(check).toMatch(/&& node svforge-check\.mjs$/);
	});

	// Real scaffold order: the base mode runs first, the dashboard overlay after.
	function scaffoldDashboard(testing: 'vitest' | 'playwright'): Map<string, string> {
		const sv = fakeSv();
		applyBaseMode(asSvApi(sv), { '/lib/base.ts': 'base' });
		applyDashboardMode(asSvApi(sv), { '/lib/base.ts': 'base' }, {}, testing);
		return sv.files;
	}

	it('dashboard mode (vitest) keeps the chained design check', () => {
		expect(generatedCheckScript(scaffoldDashboard('vitest'))).toMatch(/&& node svforge-check\.mjs$/);
	});

	it('dashboard mode (playwright) keeps the chained design check', () => {
		expect(generatedCheckScript(scaffoldDashboard('playwright'))).toMatch(/&& node svforge-check\.mjs$/);
	});

	it('template package.json files stay consistent with the generated script', () => {
		for (const template of ['base', 'dashboard']) {
			const pkg = JSON.parse(
				readFileSync(join(ROOT, `packages/svforge/templates/${template}/package.json`), 'utf-8')
			);
			expect(pkg.scripts.check, `${template} template check`).toMatch(/&& node svforge-check\.mjs$/);
		}
	});
});
