// Ambient module declaration so plain `tsc` (bun run typecheck, vitest
// typecheck) accepts the .svelte imports used by the runtime component tests
// (#321). Precise per-component types live in the plain-TS contracts module
// (primitives/types.ts) which the type tests import directly; this shim only
// needs to make the module resolvable as a Svelte component.
declare module '*.svelte' {
	import type { Component } from 'svelte';

	const component: Component;
	export default component;
}

// Pre-compiled SSR fixtures generated by tests/__setup__/compile-ssr-fixtures.ts
// (vitest globalSetup) — plain ESM modules, not typed by tsc.
declare module '*.server.js' {
	const component: unknown;
	export default component;
}
declare module '*.client.js' {
	const component: unknown;
	export default component;
}
