<script lang="ts">
	import {
		AlertTriangle,
		ArrowLeft,
		ArrowUpDown,
		Award,
		Bold,
		Briefcase,
		Calendar,
		Car,
		Check,
		ChevronDown,
		ChevronLeft,
		ChevronRight,
		ChevronsLeft,
		ChevronsRight,
		CircleAlert,
		CircleCheck,
		CirclePause,
		CirclePlay,
		CircleX,
		ClipboardCopy,
		Clock,
		Coffee,
		Crown,
		ExternalLink,
		Eye,
		EyeOff,
		Inbox,
		File,
		FileText,
		Funnel,
		Gift,
		GitPullRequest,
		Hash,
		Image,
		Info,
		Italic,
		Key,
		LayoutDashboard,
		List,
		Loader2,
		LogOut,
		Mail,
		MailCheck,
		MailOpen,
		MapPin,
		Medal,
		Menu,
		MessageCircle,
		Moon,
		Package,
		Pencil,
		Phone,
		Plane,
		Play,
		Plus,
		Power,
		PowerOff,
		RefreshCw,
		Sailboat,
		Save,
		Search,
		Send,
		Settings,
		Share2,
		Shield,
		ShieldCheck,
		ShieldX,
		ShoppingCart,
		Star,
		Sun,
		Trash2,
		Trophy,
		User,
		UserCheck,
		UserMinus,
		UserPlus,
		UserX,
		Users,
		Utensils,
		Wine,
		X,
		XCircle,
		Underline,
		Strikethrough,
		ListOrdered,
		Quote,
		Code,
		Minus,
		Undo2,
		Redo2
	} from 'lucide-svelte';

	interface Props {
		name: string;
		size?: number;
		color?: string;
		class?: string;
		title?: string;
	}

	let { name, size = 16, color, class: className, title }: Props = $props();

	const iconMap: Record<string, typeof Clock> = {
		award: Award,
		circleCheck: CircleCheck,
		clock: Clock,
		circleX: CircleX,
		plane: Plane,
		car: Car,
		sailboat: Sailboat,
		mapPin: MapPin,
		suitcase: Briefcase,
		briefcase: Briefcase,
		utensils: Utensils,
		coffee: Coffee,
		wine: Wine,
		trophy: Trophy,
		medal: Medal,
		star: Star,
		shield: Shield,
		crown: Crown,
		refresh: RefreshCw,
		refreshCw: RefreshCw,
		save: Save,
		bold: Bold,
		italic: Italic,
		list: List,
		users: Users,
		mail: Mail,
		mailCheck: MailCheck,
		mailOpen: MailOpen,
		file: File,
		fileText: FileText,
		settings: Settings,
		eye: Eye,
		search: Search,
		send: Send,
		plus: Plus,
		package: Package,
		edit: Pencil,
		pencil: Pencil,
		trash2: Trash2,
		'trash-2': Trash2,
		trash: Trash2,
		power: Power,
		checkCircle2: CircleCheck,
		checkCircle: CircleCheck,
		'check-circle': CircleCheck,
		xCircle: CircleX,
		'x-circle': CircleX,
		userCheck: UserCheck,
		'user-check': UserCheck,
		userMinus: UserMinus,
		'user-minus': UserMinus,
		userX: UserX,
		'user-x': UserX,
		userPlus: UserPlus,
		'user-plus': UserPlus,
		calendar: Calendar,
		user: User,
		arrowLeft: ArrowLeft,
		arrowUpDown: ArrowUpDown,
		gift: Gift,
		hash: Hash,
		phone: Phone,
		alertCircle: CircleAlert,
		'alert-circle': CircleAlert,
		alertTriangle: AlertTriangle,
		clipboardCopy: ClipboardCopy,
		pauseCircle: CirclePause,
		play: Play,
		playCircle: CirclePlay,
		messageCircle: MessageCircle,
		logout: LogOut,
		menu: Menu,
		filter: Funnel,
		sun: Sun,
		moon: Moon,
		externalLink: ExternalLink,
		inbox: Inbox,
		image: Image,
		info: Info,
		share2: Share2,
		shoppingCart: ShoppingCart,
		x: X,
		check: Check,
		gitPullRequest: GitPullRequest,
		layoutDashboard: LayoutDashboard,
		chevronLeft: ChevronLeft,
		chevronRight: ChevronRight,
		chevronsLeft: ChevronsLeft,
		chevronsRight: ChevronsRight,
		powerOff: PowerOff,
		chevronDown: ChevronDown,
		key: Key,
		loader2: Loader2,
		eyeOff: EyeOff,
		shieldCheck: ShieldCheck,
		shieldX: ShieldX,
		underline: Underline,
		strikethrough: Strikethrough,
		listOrdered: ListOrdered,
		'list-ordered': ListOrdered,
		quote: Quote,
		code: Code,
		minus: Minus,
		undo2: Undo2,
		redo2: Redo2
	};

	const IconComponent = $derived(iconMap[name] ?? iconMap.circleCheck);
</script>

<div class="inline-flex items-center justify-center {className}" {title}>
	<IconComponent {size} {color} />
</div>
