// AUTO-GENERATED - DO NOT EDIT
export const files = {
  "/lib/utils/posts.ts": "/** Post metadata returned by getAllPosts and getPost. */\nexport interface PostMeta {\n\ttitle: string;\n\tdate: string;\n\texcerpt: string;\n\ttags: string[];\n\tslug: string;\n}\n\n/** Full post including rendered HTML content. */\nexport interface Post extends PostMeta {\n\tcontent: string;\n}\n\n// Dynamic import of all .md files in src/posts/\nconst postFiles = import.meta.glob('/src/posts/*.md');\n\nexport async function getAllPosts(): Promise<PostMeta[]> {\n\tconst posts = await Promise.all(\n\t\tObject.entries(postFiles).map(async ([path, resolver]) => {\n\t\t\tconst mod = (await resolver()) as { metadata: PostMeta };\n\t\t\tconst slug = path.split('/').pop()!.replace('.md', '');\n\t\t\treturn { ...mod.metadata, slug } as PostMeta;\n\t\t})\n\t);\n\treturn posts.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());\n}\n\n/** Get a single post by slug, including rendered HTML content. */\nexport async function getPost(slug: string): Promise<Post | null> {\n\tconst path = `/src/posts/${slug}.md`;\n\tconst resolver = postFiles[path];\n\tif (!resolver) return null;\n\n\tconst mod = (await resolver()) as { metadata: PostMeta; default: string };\n\treturn {\n\t\t...mod.metadata,\n\t\tslug,\n\t\tcontent: mod.default\n\t};\n}\n",
  "/posts/welcome.md": "---\ntitle: Welcome to your blog\ndate: 2025-01-01\nexcerpt: Your first blog post powered by MDsveX and SvelteForge.\ntags: [welcome, blog]\n---\n\n# Welcome!\n\nThis is your first blog post. Edit it in `src/posts/welcome.md`.\n\n## MDsveX features\n\nYou can use **bold**, *italic*, code blocks, and even Svelte components:\n\n```svelte\n<script>\nlet count = 0;\n</script>\n\n<button onclick={() => count++}>\nCount: {count}\n</button>\n```\n",
  "/routes/blog/+page.server.ts": "import { getAllPosts } from '$lib/utils/posts';\nimport type { PageServerLoad } from './$types';\n\nexport const load: PageServerLoad = async () => {\nreturn { posts: await getAllPosts() };\n};\n",
  "/routes/blog/+page.svelte": "<script lang=\"ts\">\nimport { Card } from '$lib/components/svforge/ui';\nimport { Badge } from '$lib/components/svforge/primitives';\nlet { data } = $props();\n</script>\n\n<svelte:head><title>Blog</title></svelte:head>\n\n<main class=\"max-w-container mx-auto px-element py-section\">\n<h1 class=\"text-4xl font-heading font-bold mb-section\">Blog</h1>\n<div class=\"grid grid-cols-1 md:grid-cols-2 gap-group\">\n{#each data.posts as post (post.slug)}\n<a href=\"/blog/{post.slug}\">\n<Card variant=\"elevated\" class=\"h-full\">\n<h2 class=\"text-xl font-heading font-bold mb-2\">{post.title}</h2>\n<p class=\"text-surface-500 mb-4\">{post.excerpt}</p>\n<div class=\"flex gap-2\">\n{#each post.tags as tag}\n<Badge size=\"sm\" variant=\"tonal\">{tag}</Badge>\n{/each}\n</div>\n<p class=\"text-sm text-surface-400 mt-4\">{new Date(post.date).toLocaleDateString()}</p>\n</Card>\n</a>\n{/each}\n</div>\n</main>\n",
  "/routes/blog/[slug]/+page.server.ts": "import { getPost } from '$lib/utils/posts';\nimport { error } from '@sveltejs/kit';\nimport type { PageServerLoad } from './$types';\n\nexport const load: PageServerLoad = async ({ params }) => {\n\tconst post = await getPost(params.slug);\n\tif (!post) throw error(404, 'Post not found');\n\treturn { post };\n};\n",
  "/routes/blog/[slug]/+page.svelte": "<script lang=\"ts\">\nlet { data } = $props();\nconst date = new Date(data.post.date).toLocaleDateString('en', { year: 'numeric', month: 'long', day: 'numeric' });\n</script>\n\n<svelte:head>\n<title>{data.post.title}</title>\n<meta name=\"description\" content={data.post.excerpt} />\n</svelte:head>\n\n<article class=\"max-w-prose mx-auto px-element py-section\">\n<a href=\"/blog\" class=\"text-primary-500 mb-4 inline-block\">← Back to blog</a>\n<h1 class=\"text-4xl font-heading font-bold mb-4\">{data.post.title}</h1>\n<p class=\"text-surface-400 mb-section\">{date}</p>\n{@html data.post.content}\n</article>\n"
};
