/**
 * Scaffolded AGENTS.md content — written to the ROOT of the generated project.
 *
 * Makes the scaffolded project AI-ready (#203): an agent working inside the
 * generated project gets the conventions without reverse-engineering them
 * from the code (the mechanism that produced #195: LLMs trained on Skeleton v4
 * "know" variant-* exists).
 *
 * NOTE: this is a TS constant written via sv.file(), NOT a template file —
 * the prebuild only ships templates/<name>/src/** (gotcha documented in the repo
 * AGENTS.md). A root template file would be silently undelivered.
 */

const SHARED = `# AGENTS.md — generated by SvelteForge

Guide for AI agents working in this project.

## Positioning

This project was scaffolded with **SvelteForge** — a fast-start boilerplate,
NOT a component library and NOT a shadcn clone.

- The base UI kit is already in \`src/lib/components/svforge/\`: Button, Input,
  Textarea, Select, Checkbox, Toggle, Card, Badge, Alert, Table + infra
  (ThemeToggle, Seo, Sitemap, Logo). **Do not rewrite them.**
- For richer components (Accordion, Tabs, Avatar, Breadcrumb, dialogs, …) use
  the official components from \`@skeletonlabs/skeleton-svelte\` directly:
  \`import { Accordion, Tabs } from '@skeletonlabs/skeleton-svelte';\`
- Do not invent a new design system — build on what's here.

## Valid Skeleton v5 classes (IMPORTANT — LLM knowledge is stale)

Skeleton v5 utilities are exclusively:

- \`preset-filled-*\` / \`preset-tonal-*\` / \`preset-outlined-*\` (+ color suffixes like \`-primary-500\`, \`-surface-400-600\`)
- component classes: \`btn\`, \`input\`, \`select\`, \`textarea\`, \`checkbox\`, \`badge\`, \`card\`, \`table\`

**BLACKLIST — these do NOT exist in v5 (nor v4):**

- \`variant-*\` — this is the OLD Skeleton v2 naming (renamed \`preset-*\` in v3)
- \`preset-ghost\` — use \`preset-outlined-*\` or \`preset-tonal-*\`
- \`alert alert-*\` — Bootstrap classes; use the \`Alert\` component (\`variant="error"\` etc.) or the dashboard \`Feedback\` component

## Component conventions (\`src/lib/components/svforge/\`)

Canonical structure (#242) — the filesystem IS the registry:

- \`primitives/\` — small generic bricks: Button, Input, Select, Textarea, Checkbox, Toggle, Badge
- \`ui/\` — composed reusable components: Card, Alert, Table, ThemeToggle, Seo, Logo, Sitemap
- \`layout/\` — page structure: Navbar, Footer

**Before creating a UI component, ALWAYS:**
1. search \`src/lib/components/svforge/primitives/\`
2. search \`src/lib/components/svforge/ui/\`
3. search \`src/lib/components/svforge/layout/\`
4. check if Skeleton already provides it: \`import { X } from '@skeletonlabs/skeleton-svelte'\`
5. create only when no reusable option exists

A domain-specific component does NOT belong in the generic design system —
keep it in its feature area (e.g. \`src/lib/features/...\` or the route folder).

## Design-system contract (#240, #313)

**Reuse first**: prefer reuse over invention. A visually less custom interface
that fully follows the design system is preferred over a bespoke interface
that introduces new patterns. Coherence > originality on first pass.

SvelteForge deliberately scaffolds a very small CSS architecture:

- \`src/routes/layout.css\` is the **single global CSS entrypoint**. Keep it as wiring only: Tailwind, Skeleton, Skeleton Svelte, fonts, plugins, the dark variant, and the import of the SvelteForge theme.
- \`src/lib/styles/svelteforge-theme.css\` is the **complete Skeleton v5 theme** and the visual source of truth for palettes, surfaces, brand, root backgrounds, typography, radius/shapes, borders, rings and outlines.
- There is intentionally **no generic \`tokens.css\` or \`index.css\` layer** in the scaffold. Use normal Tailwind utilities for local layout and spacing (for example \`p-4\`, \`gap-6\`, \`max-w-7xl\`).

Before adding global CSS or a custom visual token, ask: **can Skeleton express this through the theme, a preset, or an existing utility?** If yes, use Skeleton. Only introduce a project-specific abstraction after a concrete, repeated product need exists and Skeleton/Tailwind do not already cover it.

MUST:
- inspect the SvelteForge catalog before writing UI
- reuse existing SvelteForge components before creating new ones
- use Skeleton/Skeleton Svelte for UI primitives and interaction patterns
- change \`svelteforge-theme.css\` first for global visual decisions covered by Skeleton
- use standard Tailwind utilities for local structure, whitespace and responsive layout
- keep pages composition-oriented and thin

MUST NOT:
- install another UI kit
- create a duplicate Button/Input/Card/Dialog/Tabs/Menu/etc. when Skeleton or SvelteForge already provides it
- create project-local one-off design primitives without justification
- create a parallel global palette/token system for colors, surfaces, radius, focus, hover or shadows by default
- add global visual overrides in \`layout.css\` when the Skeleton theme or presets already own the behavior
- redesign the global visual language inside a feature PR

Run \`npx svforge check\` before finishing a feature — it flags ERROR
violations (second UI kit, duplicated primitives) and WARN (arbitrary values).

Components wrap Skeleton classes + Tailwind only — never raw CSS
- \`cn()\` + \`class\` prop on every component (merge/override)
- \`HTMLAttributes<T>\` from \`svelte/elements\` for native attribute extension
- \`$bindable()\` declared in the Props interface
- Phosphor icons: \`import X from 'phosphor-svelte/lib/IconName'\`

## Theme

- The complete Skeleton v5 theme lives in \`src/lib/styles/svelteforge-theme.css\` under \`[data-theme='svelteForge']\`.
- Global CSS wiring lives in \`src/routes/layout.css\`; keep it minimal and non-visual.
- Dark mode uses the \`data-mode\` attribute / ThemeToggle component.
- For a project-wide visual change that Skeleton supports, change the theme rather than adding a global override.
- Add a project-specific token/effects layer only later, when a real repeated use case proves it is needed.

## Project commands

\`\`\`bash
bun run dev      # dev server
bun run build    # production build
bun run check    # svelte-check
bun run test     # vitest (dashboard: baseline auth/admin tests)
\`\`\`

## i18n (Paraglide FR/EN — #239)

This project ships **Paraglide** (compiler-first i18n) with **fr** (baseLocale) and **en**.

MUST:
- use Paraglide for static user-facing UI copy: \`import * as m from '$lib/paraglide/messages.js'\`
- add/update BOTH \`messages/fr.json\` and \`messages/en.json\` for every UI copy change
- reuse existing message keys when semantics are identical (\`common_save\`, \`common_cancel\`…)
- use domain-oriented message names (\`users_create\`, not \`blue_button_text\`)

MUST NOT:
- hardcode static user-facing copy in Svelte components without a justified exception
- create another i18n/message abstraction
- update only one locale — a feature is not done until both fr and en exist

Editorial content (blog/MDsveX, CMS/DB) does NOT belong in the catalogs.

## LLM resources (offline knowledge is likely stale)

If you need Skeleton or Svelte specifics, fetch the FRESH docs rather than
trusting training memory:

- \`https://skeleton.dev/llms-full.txt\`
- \`https://svelte.dev/llms-full.txt\`
`;

const DASHBOARD = `

## Dashboard patterns (this project is a SvelteForge dashboard)

- **Auth**: Better Auth. Session in \`locals.user\` / \`locals.session\` (\`src/hooks.server.ts\`). Login via \`src/routes/login\`, first admin via \`/setup\` (dev only).
- **Admin guard**: \`requireAdmin()\` in \`src/routes/(app)/admin/*/+page.server.ts\` — every action calls it BEFORE touching formData or the db.
- **SvelteKit action responses**: \`{ type, data }\` — read the message at \`result.data?.message\`, NEVER \`result.message\` (always undefined).
- **Server errors**: never leak \`e.message\` to the UI — return a generic message.
- **DB**: Drizzle + PostgreSQL. Schema in \`src/lib/server/db/schema.ts\`, config \`drizzle.config.ts\` at the root (dialect postgresql). Env in \`.env\` (copy \`.env.example\` — local / Docker / managed connection strings).
- **Validation**: zod schemas in \`src/lib/server/schemas.ts\`.
- **Setup**: \`bash scripts/setup.sh\` creates \`.env\`, generates \`BETTER_AUTH_SECRET\`, pushes the schema.
### Golden references (#267) — imitate these screens when building new UI

The admin screens are canonical examples agents should copy:

- **\`/admin/users\`** — CRUD data table: the SvelteForge \`Table\` primitive (columns + \`children\` slot for avatar/badge/actions), search filter, create/edit modal (\`Card\` + \`Input\`), delete confirmation, \`Feedback\` for success/error, empty state. Never hand-roll a raw \`<table>\` (see catalogue \`avoid\`).
- **\`/admin\`** — stats cards (\`Card variant="elevated"\`) + recent list with \`Badge\` status.
- **\`/admin/settings\`** — form with client-side validation + \`Feedback\`.
- **\`AdminLayout\`** — sidebar/mobile drawer with \`aria-expanded\`, \`aria-current\`, labelled navigation.
- **All UI copy is i18n via Paraglide**: import \`* as m from '$lib/paraglide/messages.js'\` and call \`m.key()\` — never hard-code user-visible text. Keys live in \`messages/fr.json\` + \`messages/en.json\` (keep parity).
`;

export function scaffoldedAgents(template: 'base' | 'dashboard'): string {
	return SHARED + (template === 'dashboard' ? DASHBOARD : '');
}
