/**
 * Scaffolded AGENTS.md content — written to the ROOT of the generated project.
 *
 * Makes the scaffolded project AI-ready (#203): an agent working inside the
 * generated project gets the conventions without reverse-engineering them
 * from the code (the mechanism that produced #195: LLMs trained on Skeleton v4
 * "know" variant-* exists).
 *
 * NOTE: this is a TS constant written via sv.file(), NOT a template file —
 * the prebuild only ships templates/<name>/src/** (gotcha documented in the repo
 * AGENTS.md). A root template file would be silently undelivered.
 */

import { SKELETON_PRIMITIVES, SKELETON_VERSIONS as SKELETON_INVENTORY } from './skeleton-inventory';

const SHARED = (primitives: string, versions: { css: string; svelte: string }) => `# AGENTS.md — generated by SvelteForge

Guide for AI agents working in this project.

## Positioning

This project was scaffolded with **SvelteForge** — a fast-start boilerplate,
NOT a component library and NOT a shadcn clone.

- The base UI kit is already in \`src/lib/components/svforge/\`: Button, Input,
  Textarea, Select, Checkbox, Toggle, Card, Badge, Alert, Table + infra
  (ThemeToggle, Seo, Sitemap, Logo). **Do not rewrite them.**
- For richer components use the official components from
  \`@skeletonlabs/skeleton-svelte\` directly. The full installed inventory
  (${primitives}) is protected by \`svforge check\`.
- Do not invent a new design system — build on what's here.

## Valid Skeleton v5 classes (IMPORTANT — LLM knowledge is stale)

This project ships with Skeleton ${versions.css} / Skeleton Svelte ${versions.svelte}.
Skeleton v5 utilities are exclusively:

- \`preset-filled-*\` / \`preset-tonal-*\` / \`preset-outlined-*\` (+ color suffixes like \`-primary-500\`, \`-surface-400-600\`)
- component classes: \`btn\`, \`btn-icon\`, \`badge\`, \`chip\`, \`card\`, \`input\`, \`select\`, \`textarea\`, \`checkbox\`, \`table\`, \`label\`
- radius/shape: \`corner-shape-*\` — NOT \`rounded-container\` / custom radii
- sizes: \`btn-xs…btn-9xl\`, \`btn-icon-*\` — NOT \`btn-md\`, NOT \`badge-sm\`

**BLACKLIST — these do NOT exist in v5 (nor v4):**

- \`variant-*\` — this is the OLD Skeleton v2 naming (renamed \`preset-*\` in v3)
- \`preset-ghost\` — use \`preset-outlined-*\` or \`preset-tonal-*\`
- \`alert alert-*\` — Bootstrap classes; use the \`Alert\` component (\`variant="error"\` etc.) or the dashboard \`Feedback\` component
- \`btn-md\`, \`badge-sm\`, \`preset-tonal-info\`, \`input-error\` — invented utilities; \`svforge check\` rejects them

\`svforge check\` validates every class against the actually installed Skeleton inventory: inventing a
utility or stacking two incompatible primitives fails before merge.

## Advisory vs enforced

This file is **advisory**: it tells agents what to prefer. The mechanical
enforcement is \`npx svforge check\` — design-system violations (second UI kit,
duplicated primitives, invented utilities) fail THERE, not here. Other agent
instruction files (CLAUDE.md, .github/copilot-instructions.md,
.cursor/rules/svforge.mdc) are generated bridges to this one: they are derived
from the same source at scaffold time and must not be edited separately.

## Component conventions (\`src/lib/components/svforge/\`)

Canonical structure (#242) — the filesystem IS the registry:

- \`primitives/\` — small generic bricks: Button, Input, Select, Textarea, Checkbox, Toggle, Badge
- \`ui/\` — composed reusable components: Card, Alert, Table, ThemeToggle, Seo, Logo, Sitemap
- \`layout/\` — page structure: Navbar, Footer

**Before creating a UI component, ALWAYS:**
1. search \`src/lib/components/svforge/primitives/\`
2. search \`src/lib/components/svforge/ui/\`
3. search \`src/lib/components/svforge/layout/\`
4. check if Skeleton already provides it: \`import { X } from '@skeletonlabs/skeleton-svelte'\`
5. create only when no reusable option exists

A domain-specific component does NOT belong in the generic design system —
keep it in its feature area (e.g. \`src/lib/features/...\` or the route folder).

## Design-system contract (#240, #313)

**Reuse first**: prefer reuse over invention. A visually less custom interface
that fully follows the design system is preferred over a bespoke interface
that introduces new patterns. Coherence > originality on first pass.

SvelteForge deliberately scaffolds a very small CSS architecture:

- \`src/routes/layout.css\` is the **single global CSS entrypoint**. Keep it as wiring only: Tailwind, Skeleton, Skeleton Svelte, fonts, plugins, the dark variant, and the import of the SvelteForge theme.
- \`src/lib/styles/svelteforge-theme.css\` is the **complete Skeleton v5 theme** and the visual source of truth for palettes, surfaces, brand, root backgrounds, typography, radius/shapes, borders, rings and outlines.
- There is intentionally **no generic \`tokens.css\` or \`index.css\` layer** in the scaffold. Use normal Tailwind utilities for local layout and spacing (for example \`p-4\`, \`gap-6\`, \`max-w-7xl\`).

Before adding global CSS or a custom visual token, ask: **can Skeleton express this through the theme, a preset, or an existing utility?** If yes, use Skeleton. Only introduce a project-specific abstraction after a concrete, repeated product need exists and Skeleton/Tailwind do not already cover it.

MUST:
- inspect the SvelteForge catalog before writing UI
- reuse existing SvelteForge components before creating new ones
- use Skeleton/Skeleton Svelte for UI primitives and interaction patterns
- change \`svelteforge-theme.css\` first for global visual decisions covered by Skeleton
- use standard Tailwind utilities for local structure, whitespace and responsive layout
- keep pages composition-oriented and thin

MUST NOT:
- install another UI kit
- create a duplicate Button/Input/Card/Dialog/Tabs/Menu/etc. when Skeleton or SvelteForge already provides it
- create project-local one-off design primitives without justification
- create a parallel global palette/token system for colors, surfaces, radius, focus, hover or shadows by default
- add global visual overrides in \`layout.css\` when the Skeleton theme or presets already own the behavior
- redesign the global visual language inside a feature PR

Run \`npx svforge check\` before finishing a feature — it flags ERROR
violations (second UI kit, duplicated primitives) and WARN (arbitrary values).

Components wrap Skeleton classes + Tailwind only — never raw CSS
- \`cn()\` + \`class\` prop on every component (merge/override)
- \`HTMLAttributes<T>\` from \`svelte/elements\` for native attribute extension
- \`$bindable()\` declared in the Props interface
- Phosphor icons: \`import X from 'phosphor-svelte/lib/IconName'\`

## Theme

- The complete Skeleton v5 theme lives in \`src/lib/styles/svelteforge-theme.css\` under \`[data-theme='svelteForge']\`.
- Global CSS wiring lives in \`src/routes/layout.css\`; keep it minimal and non-visual.
- Dark mode uses the \`data-mode\` attribute / ThemeToggle component.
- For a project-wide visual change that Skeleton supports, change the theme rather than adding a global override.
- Add a project-specific token/effects layer only later, when a real repeated use case proves it is needed.

## Project commands

\`\`\`bash
bun run dev      # dev server
bun run build    # production build
bun run check    # svelte-check
bun run test     # vitest (dashboard: baseline auth/admin tests)
\`\`\`

## i18n (Paraglide FR/EN — #239)

This project ships **Paraglide** (compiler-first i18n) with **fr** (baseLocale) and **en**.

MUST:
- use Paraglide for static user-facing UI copy: \`import * as m from '$lib/paraglide/messages.js'\`
- add/update BOTH \`messages/fr.json\` and \`messages/en.json\` for every UI copy change
- reuse existing message keys when semantics are identical (\`common_save\`, \`common_cancel\`…)
- use domain-oriented message names (\`users_create\`, not \`blue_button_text\`)

MUST NOT:
- hardcode static user-facing copy in Svelte components without a justified exception
- create another i18n/message abstraction
- update only one locale — a feature is not done until both fr and en exist

Editorial content (blog/MDsveX, CMS/DB) does NOT belong in the catalogs.

## LLM resources (offline knowledge is likely stale)

If you need Skeleton or Svelte specifics, fetch the FRESH docs rather than
trusting training memory:

- \`https://skeleton.dev/llms-full.txt\`
- \`https://svelte.dev/llms-full.txt\`
`;

const DASHBOARD = `

## Dashboard patterns (this project is a SvelteForge dashboard)

- **Auth**: Better Auth. Session in \`locals.user\` / \`locals.session\` (\`src/hooks.server.ts\`). Login via \`src/routes/login\`, first admin via \`/setup\` (dev only).
- **Admin guard**: \`requireAdmin()\` in \`src/routes/(app)/admin/*/+page.server.ts\` — every action calls it BEFORE touching formData or the db.
- **SvelteKit action responses**: \`{ type, data }\` — read the message at \`result.data?.message\`, NEVER \`result.message\` (always undefined).
- **Server errors**: never leak \`e.message\` to the UI — return a generic message.
- **DB**: Drizzle + PostgreSQL. Schema in \`src/lib/server/db/schema.ts\`, config \`drizzle.config.ts\` at the root (dialect postgresql). Env in \`.env\` (copy \`.env.example\` — local / Docker / managed connection strings).
- **Validation**: zod schemas in \`src/lib/server/schemas.ts\`.
- **Setup**: \`bash scripts/setup.sh\` creates \`.env\`, generates \`BETTER_AUTH_SECRET\`, pushes the schema.
### Golden references (#267) — imitate these screens when building new UI

The admin screens are canonical examples agents should copy:

- **\`/admin/users\`** — CRUD data table: the SvelteForge \`Table\` primitive (columns + \`children\` slot for avatar/badge/actions), search filter, create/edit modal (\`Card\` + \`Input\`), delete confirmation, \`Feedback\` for success/error, empty state. Never hand-roll a raw \`<table>\` (see catalogue \`avoid\`).
- **\`/admin\`** — stats cards (\`Card variant="elevated"\`) + recent list with \`Badge\` status.
- **\`/admin/settings\`** — form with client-side validation + \`Feedback\`.
- **\`AdminLayout\`** — sidebar/mobile drawer with \`aria-expanded\`, \`aria-current\`, labelled navigation.
- **All UI copy is i18n via Paraglide**: import \`* as m from '$lib/paraglide/messages.js'\` and call \`m.key()\` — never hard-code user-visible text. Keys live in \`messages/fr.json\` + \`messages/en.json\` (keep parity).
`;

export function scaffoldedAgents(template: 'base' | 'dashboard'): string {
	const shared = SHARED(SKELETON_PRIMITIVES.join(', '), SKELETON_INVENTORY);
	return shared + (template === 'dashboard' ? DASHBOARD : '');
}

/**
 * Agent instruction files written to the ROOT of the generated project
 * (#347). Strategy: agent-agnostic — `AGENTS.md` is the canonical file, and
 * every other instruction file is a GENERATED BRIDGE derived from that same
 * source so the variants are identical at scaffold time. What each covers:
 *
 * - `CLAUDE.md` — Claude Code reads CLAUDE.md, NOT AGENTS.md
 *   (code.claude.com/docs/en/memory); the documented `@AGENTS.md` import
 *   pulls the canonical file in without duplicating content.
 * - `GEMINI.md` — Gemini CLI reads GEMINI.md by default, NOT AGENTS.md
 *   (github.com/google-gemini/gemini-cli docs, gemini-md.md); the documented
 *   `@AGENTS.md` import pulls the canonical file in without duplicating
 *   content.
 * - `.github/copilot-instructions.md` — GitHub Copilot's instruction file; it
 *   has no AGENTS.md import mechanism, so the canonical content is embedded.
 * - `.cursor/rules/svforge.mdc` — Cursor's project-rule location
 *   (`alwaysApply: true`), with the canonical content embedded.
 *
 * Copilot and Cursor files are MATERIALIZED COPIES: they can drift after a
 * later AGENTS.md edit. `svforge context` re-materializes them from the
 * canonical file (`syncInstructionBridges`), and the scaffolded
 * `svforge-check.mjs` warns when a copy is stale.
 *
 * All files here are ADVISORY instructions. Mechanical enforcement stays in
 * `svforge check` — instruction files are never the only guardrail.
 */
export function agentInstructionFiles(template: 'base' | 'dashboard'): Record<string, string> {
	const canonical = scaffoldedAgents(template);
	return {
		'AGENTS.md': canonical,
		'CLAUDE.md':
			'<!-- Generated by SvelteForge (#347): Claude Code reads CLAUDE.md; @AGENTS.md imports the canonical agent instructions. -->\n\n@AGENTS.md\n',
		'GEMINI.md':
			'<!-- Generated by SvelteForge (#347): Gemini CLI reads GEMINI.md by default; @AGENTS.md imports the canonical agent instructions. -->\n\n@AGENTS.md\n',
		'.github/copilot-instructions.md':
			'<!-- Generated by SvelteForge (#347) from the same source as AGENTS.md — run `npx svforge context` to re-sync after editing AGENTS.md. -->\n\n' +
			canonical,
		'.cursor/rules/svforge.mdc':
			'---\n' +
			'description: SvelteForge project conventions (generated)\n' +
			'globs:\n' +
			'alwaysApply: true\n' +
			'---\n\n' +
			canonical +
			'\n'
	};
}

/** Bridges that embed the canonical content (materialized copies). */
export const MATERIALIZED_BRIDGES = ['.github/copilot-instructions.md', '.cursor/rules/svforge.mdc'] as const;

/**
 * Re-materialize the copied instruction bridges from the project's current
 * AGENTS.md (#347 review). The @-import bridges (CLAUDE.md, GEMINI.md) never
 * drift; the Copilot/Cursor copies do. Returns the files written.
 */
export function syncInstructionBridges(
	fs: typeof import('node:fs'),
	path: typeof import('node:path'),
	projectRoot: string
): string[] {
	const canonicalPath = path.join(projectRoot, 'AGENTS.md');
	if (!fs.existsSync(canonicalPath)) return [];
	const canonical = fs.readFileSync(canonicalPath, 'utf-8');
	const written: string[] = [];
	for (const bridge of MATERIALIZED_BRIDGES) {
		const bridgePath = path.join(projectRoot, bridge);
		if (!fs.existsSync(bridgePath)) continue; // never create what the scaffold did not
		const current = fs.readFileSync(bridgePath, 'utf-8');
		if (current.includes(canonical)) continue; // already in sync
		// The generated prefix is a copilot HTML comment or a Cursor YAML
		// frontmatter; everything after it is the canonical content.
		const prefixMatch = bridge.endsWith('.mdc')
			? current.match(/^-{3}\n[\s\S]*?\n-{3}\n\n/)
			: current.match(/^<!--[\s\S]*?-->\n\n/);
		if (!prefixMatch) continue; // unknown shape: leave it alone
		const updated = prefixMatch[0] + canonical + (bridge.endsWith('.mdc') ? '\n' : '');
		fs.writeFileSync(bridgePath, updated);
		written.push(bridge);
	}
	return written;
}
