<script lang="ts">
	import {
		Airplane,
		ArrowClockwise,
		ArrowCounterClockwise,
		ArrowLeft,
		ArrowSquareOut,
		ArrowsClockwise,
		ArrowsDownUp,
		Bell,
		BellRinging,
		Briefcase,
		Calendar,
		Car,
		CaretDown,
		CaretLeft,
		CaretLineLeft,
		CaretLineRight,
		CaretRight,
		ChatCircle,
		Check,
		CheckCircle,
		Clock,
		Coffee,
		Code,
		Copy,
		Crown,
		EnvelopeOpen,
		EnvelopeSimple,
		Eye,
		EyeSlash,
		File,
		FileText,
		FloppyDisk,
		Funnel,
		Gear,
		Gift,
		GitPullRequest,
		Hash,
		Image,
		Inbox,
		Info,
		Key,
		List,
		ListNumbers,
		MapPin,
		Medal,
		Menu,
		Minus,
		Moon,
		Package,
		PaperPlaneTilt,
		PauseCircle,
		Pencil,
		Phone,
		Play,
		PlayCircle,
		Plus,
		Power,
		Quotes,
		Sailboat,
		Search,
		SealCheck,
		ShareNetwork,
		Shield,
		ShieldCheck,
		ShieldWarning,
		ShoppingCart,
		SignOut,
		Spinner,
		SquaresFour,
		Star,
		Sun,
		TextB,
		TextItalic,
		TextStrikethrough,
		TextUnderline,
		Trash,
		Trophy,
		User,
		UserCheck,
		UserMinus,
		UserPlus,
		UserX,
		Users,
		Utensils,
		Warning,
		WarningCircle,
		Wine,
		X,
		XCircle
	} from 'phosphor-svelte';

	interface Props {
		name: string;
		size?: number | string;
		color?: string;
		class?: string;
		title?: string;
	}

	let { name, size = 16, color, class: className, title }: Props = $props();

	const iconMap: Record<string, typeof Clock> = {
		award: Medal,
		circleCheck: CheckCircle,
		clock: Clock,
		circleX: XCircle,
		plane: Airplane,
		car: Car,
		sailboat: Sailboat,
		mapPin: MapPin,
		suitcase: Briefcase,
		briefcase: Briefcase,
		utensils: Utensils,
		coffee: Coffee,
		wine: Wine,
		trophy: Trophy,
		medal: Medal,
		star: Star,
		shield: Shield,
		crown: Crown,
		refresh: ArrowsClockwise,
		refreshCw: ArrowsClockwise,
		save: FloppyDisk,
		bold: TextB,
		italic: TextItalic,
		list: List,
		users: Users,
		mail: EnvelopeSimple,
		mailCheck: SealCheck,
		mailOpen: EnvelopeOpen,
		file: File,
		fileText: FileText,
		settings: Gear,
		eye: Eye,
		search: Search,
		send: PaperPlaneTilt,
		plus: Plus,
		package: Package,
		edit: Pencil,
		pencil: Pencil,
		trash2: Trash,
		'trash-2': Trash,
		trash: Trash,
		power: Power,
		checkCircle2: CheckCircle,
		checkCircle: CheckCircle,
		'check-circle': CheckCircle,
		xCircle: XCircle,
		'x-circle': XCircle,
		userCheck: UserCheck,
		'user-check': UserCheck,
		userMinus: UserMinus,
		'user-minus': UserMinus,
		userX: UserX,
		'user-x': UserX,
		userPlus: UserPlus,
		'user-plus': UserPlus,
		calendar: Calendar,
		user: User,
		arrowLeft: ArrowLeft,
		arrowUpDown: ArrowsDownUp,
		gift: Gift,
		hash: Hash,
		phone: Phone,
		alertCircle: WarningCircle,
		'alert-circle': WarningCircle,
		alertTriangle: Warning,
		clipboardCopy: Copy,
		pauseCircle: PauseCircle,
		play: Play,
		playCircle: PlayCircle,
		messageCircle: ChatCircle,
		logout: SignOut,
		menu: Menu,
		filter: Funnel,
		sun: Sun,
		moon: Moon,
		externalLink: ArrowSquareOut,
		inbox: Inbox,
		image: Image,
		info: Info,
		share2: ShareNetwork,
		shoppingCart: ShoppingCart,
		x: X,
		check: Check,
		gitPullRequest: GitPullRequest,
		layoutDashboard: SquaresFour,
		chevronLeft: CaretLeft,
		chevronRight: CaretRight,
		chevronsLeft: CaretLineLeft,
		chevronsRight: CaretLineRight,
		powerOff: Power,
		chevronDown: CaretDown,
		key: Key,
		loader2: Spinner,
		eyeOff: EyeSlash,
		shieldCheck: ShieldCheck,
		shieldX: ShieldWarning,
		underline: TextUnderline,
		strikethrough: TextStrikethrough,
		listOrdered: ListNumbers,
		'list-ordered': ListNumbers,
		quote: Quotes,
		code: Code,
		minus: Minus,
		undo2: ArrowCounterClockwise,
		redo2: ArrowClockwise,
		bell: Bell,
		bellRinging: BellRinging
	};

	const IconComponent = $derived(iconMap[name] ?? iconMap.circleCheck);
</script>

<div class="inline-flex items-center justify-center {className}" {title}>
	<IconComponent {size} {color} />
</div>
