/**
 * Prebuild script — reads template files and generates src/templates.ts
 * Each file is stored as a Record<filePath, fileContent> so the addon
 * can copy them into the target project via sv.file().
 */
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

const TEMPLATES_DIR = join(import.meta.dirname, '..', 'templates');
const OUTPUT_FILE = join(import.meta.dirname, '..', 'src', 'templates.ts');

function walk(dir: string): string[] {
	return readdirSync(dir).flatMap((f) => {
		const p = join(dir, f);
		return statSync(p).isDirectory() ? walk(p) : [p];
	});
}

const files: Record<string, string> = {};

for (const fullPath of walk(TEMPLATES_DIR)) {
	const rel = relative(TEMPLATES_DIR, fullPath);
	// Normalize to forward slashes
	const key = '/' + rel.split('\\').join('/');
	files[key] = readFileSync(fullPath, 'utf-8');
}

const output = `// Auto-generated by scripts/prebuild.ts — DO NOT EDIT
export const files: Record<string, string> = ${JSON.stringify(files, null, '\t')};\n`;

writeFileSync(OUTPUT_FILE, output);
console.log(`Generated ${OUTPUT_FILE} with ${Object.keys(files).length} files.`);
